security:
  oauth2:
    client:
      clientId: 311089469237665
      clientSecret: b49a74fe88759889048353c763204846
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/stubprojectdb?createDatabaseIfNotExist=true
  username: root
  password: root
hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
  hbm2ddl:
      auto: update
  show_sql: true
  format_sql: false